### ISSUE TITLE
json_decode() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Niels-P** [fourstacks/nova-repeatable-fields#25]
Hi everyone,

I'm trying this package out, but it seems I can't get it to work.
I've followed the instructions as presented in the repo, but get the following error:

`json_decode() expects parameter 1 to be string, array given`

I added the following things to my resource;
`
use Fourstacks\NovaRepeatableFields\Repeater;
Repeater::make('Benefits')->addField(['label' => 'benefits']),
`

In my model I've added the following cast properties;
`protected $casts = ['benefits' => 'array'];`

However, it does not seem to work! Can anyone give me some advise, help me out? Thank you!

**Comment by fourstacks** [comment]
Fixed in v1.1.0

**Comment by Nassu972** [comment]
Still having same issue with 1.2.0, fixed it with 
```
protected function fillAttributeFromRequest(NovaRequest $request,
                                                $requestAttribute,
                                                $model,
                                                $attribute)
    {
        if ($request->exists($requestAttribute)) {
            $model->{$attribute} = $request[$requestAttribute];
        }
    }
```

**Comment by Niels-P** [comment]
> Still having same issue with 1.2.0, fixed it with
> 
> ```
> protected function fillAttributeFromRequest(NovaRequest $request,
>                                                 $requestAttribute,
>                                                 $model,
>                                                 $attribute)
>     {
>         if ($request->exists($requestAttribute)) {
>             $model->{$attribute} = $request[$requestAttribute];
>         }
>     }
> ```

Good fix! It's indeed still an issue, I've solved it the same way as you did.
